#!/usr/bin/env Rscript

dupl_chunk_names <- function () {
    x <- readLines ("_quarto.yml")

    rmd <- gsub ("^.*\\-\\s+", "", grep ("\\.Rmd$", x, value = TRUE))

    ptn <- "^\\`\\`\\`\\{r\\s?"
    chunk_names <- list ()
    for (f in rmd) {
        x <- readLines (f)
        x <- gsub (ptn, "", x [grep (ptn, x)])
        # then remove all stuff after first comma
        chunk_names [[length (chunk_names) + 1]] <- gsub (",.*$", "", x)
    }
    names (chunk_names) <- rmd
    chunk_names <- gsub ("\\}$", "", unlist (chunk_names))

    repeats <- chunk_names [which (duplicated (chunk_names [chunk_names != ""]))]
    for (r in repeats) {
        n <- vapply (names (chunk_names) [which (chunk_names == r)], function (i)
                     gsub ("[0-9]+$", "", i), character (1), USE.NAMES = FALSE)
        message ("Repeated chunk name [", unname (r),
                 "] in [", paste0 (unique (n), collapse = ", "), "]")
    }

    blanks <- vapply (names (chunk_names) [which (chunk_names == "")], function (i)
                      substring (i, 1, nchar (i) - 1), character (1), USE.NAMES = FALSE)
    blanks <- unique (blanks)
    if (length (blanks) > 0)
        message ("There are unnamed chunks in [", paste0 (blanks, collapse = ", "), "]")

    return (length (repeats) == 0 & length (blanks) == 0)
}
if (!dupl_chunk_names ())
    stop ("Files contain duplicated or blank chunk names")
