<!-- Edit the .Rmd not the .md file -->

## Probability Distributions {#standards-distributions}

This sub-section details standards for Software which represents, transforms,
or otherwise processes probability distributions. Unlike most other categories
of standards, packages which fit in this category will also generally be
expected to fit into at least one other category of statistical software.
Reflecting that expectation, standards for probability distributions will be
expected to only pertain to some (potentially small) portion of code in any
package.

Packages which utilise distributional functions to extract uni- or
multi-variate estimates as a final algorithmic step, for example to provide
numeric probability estimates, are not considered probability distributions
software, and are not required to comply with these standards.

These standards apply to any package which performs operations on probability
distributions. Operations include, but are not limited to, transformation,
representation, convolution, integration, inversion, fitting, or re-scaling.
The definition of probability distributions software ultimately depends on the
notion of an "operation," and it is ultimately up to package authors, in
conversation with reviewers,  to decide whether or not these *Probability
Distribution Standards* might apply. If in doubt, the same principle applies
here as to all other categories of standards: If at least half of the following
standards apply, or could conceivably be applied, to a package, then it should
be considered a probability distributions package.


### Documentation{#PD_documentation}

- [**PD1.0**]{#PD1_0} *Software should provide references justifying choice and
  usage of particular probability distributions.*

This standard applies, for example, to all cases where results of some
algorithm are assumed to comply with some "known" statistical distribution, and
are accordingly transformed or summarised. Software should then provide
references demonstrating that such distributional properties may indeed be
assumed to apply. This standard will not apply to any routines for general
processing of probability distributions.

### Packages for Representing Distributions{#PD_representation}

These standards encourage the use of packages for general representation of
probability distributions, especially as this allows distributional assumptions
to be readily tested, refined, and updated, rather than remaining hard-coded
and effectively fixed. The [CRAN Task View on Probability
Distributions](https://cran.r-project.org/web/views/Distributions.html) has a
sub-section under [the "Miscellaneous"
heading](https://cran.r-project.org/web/views/Distributions.html#Misc) on
*Unified interface to handle distributions*. Packages mentioned in that
sub-section include:

- The core [`stats`](https://cran.r-project.org/web/packages/STAT/index.html) 
  package distributed wtih base `R`;
- The [`distr` family of packages](https://distr.r-forge.r-project.org/), which
  offer an extremely powerful and flexibility range of S4-class objects for
  representing and manipulating probability distributions;
- The [`distributions3`](https://github.com/alexpghayes/distributions3) and
  [`distributional`](https://github.com/mitchelloharawild/distributional)
  packages for representing and manipulating probability distributions as S3
  objects; and
- The [`distr6` package](https://github.com/alan-turing-institute/distr6/) for
  distributions as [`R6`](https://r6.r-lib.org) objects.

The follow standard should be adhered to where possible:

- [**PD2.0**]{#PD2_0} *Where possible, software should represent probability
  distributions using a package for general representation.*

Any one package will generally only be able to fulfil either this or the
preceding standard (**PD1.0**): it will either use a particular distribution,
and thus need to adhere to **PD1.0**, or it will treat distributions more
generally, and thus need to adhere to **PD2.0**.


### Algorithms{#PD_algorithms}


- [**PD3.0**]{#PD3_0} *Manipulation of probability distributions should very
  generally be analytic, with numeric manipulations only implemented with clear
  justification (ideally including references).*

An exemplary discussion of conditions under which numeric manipulations may be
considered is provided in the [*Analytical and Numerical Methods*
vignette](https://alan-turing-institute.github.io/distr6/articles/webs/analytic_and_numeric_methods.html)
of the [`distr6` package](https://alan-turing-institute.github.io/distr6/).

- [**PD3.1**]{#PD3_1} *Operations on probability distributions should generally
  be contained within separate functions which themselves accept the names of
  the distributions as one input parameter.*

This standard enables assumptions on distributions to be readily tested and
updated, and applies even to packages which use only one single and specific
distribution in accordance with [**PD1.0**](#PD1_0). The names of distributions
are generally best passed as single character values, processed via calls like
`do.call(get(dist_name), list(args))` (although many other approaches are also
possible). This standard is also important for the testing standards which
follow.

#### Optimisation algorithms

The following standard applies to operations on probability distributions which
require calls to optimisation algorithms such as
[`optimize()`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optimize.html),
[`optim()`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optim.html),
or any equivalent numerical optimisation routines from `stats` or other
packages.

- [**PD3.2**]{#PD3_2} *Use of optimisation routines to estimate parameters from
  probability distributions should explicitly specify and explain values of all
  parameters, including all uses of default parameters.*
- [**PD3.3**]{#PD3_3} *Return objects which include values generated from
  optimisation algorithms should include information on optimisation algorithm
  and performance, minimally including the name of the algorithm used, the
  convergence tolerance, and the number of iterations.*

See below for additional [testing standards](#PD_testing) which also apply to
probability distribution packages which use optimisation algorithms.

#### Integration algorithms

- [**PD3.4**]{#PD3_4} *Use of routines to integrate probability distributions
  should explicitly document conditions under which integrals are expected to
  remain stable, and ideally include pre-processing checks for potentially
  unstable behaviour.*
- [**PD3.5**]{#PD3_5} *Integration routines should only rely on discrete
  summation where such use can be justified (for example, through providing a
  literature reference), in which case the following applies:*
  - [**PD3.5a**]{#PD3_5a} *Use of discrete summation to approximate integrals
    must demonstrate that the Reimann sum has a finite limit (or, equivalently,
    must explicitly describe the conditions under which the sum may be expected
    to be finite).*

See below for additional [testing standards](#PD_testing) which also apply to
probability distribution packages which use integration algorithms.

### Fitting Distributions{#PD_fitting}

Fitting distributions is an important component of many statistical
analyses, yet R currently has only two packages for general distributional
fitting: [`fitdistrplus`](https://github.com/aursiber/fitdistrplus) and
[`fitteR`](https://cran.r-project.org/web/packages/fitteR/index.html). The
field of distributional fitting is currently in very active development, and
there are no notably "stable" approaches nor widely-used algorithms. This is
reflected in the almost complete lack of mention of distributional fitting in
the [*CRAN Task View on Probability
Distributions*](https://cran.r-project.org/web/views/Distributions.html). The
very last point in the current version of that *Task View* describes "*Parameter
Estimation*", and links to both of these packages.

Given this dynamically evolving nature of code and algorithms for
distributional fitting, this book currently provides no standards for this
aspect. We nevertheless encourage any authors using or implementing
distributional fitting procedures to help develop standards, for which we
recommend use of the [GitHub discussions channel for these
standards](https://github.com/ropensci/statistical-software-review-book/discussions/58).

### Testing{#PD_testing}

The following standards refer and apply to *functions which process probability
distributions*, meaning functions defined in accordance with **PD2.1**, above.
Such functions are referred to in the following standards as *probability
distribution functions*.

- [**PD4.0**]{#PD4_0} *The numeric outputs of probability distribution
  functions should be tested, not just output structures. These tests should
  generally be tests for numeric equality.*

Numeric equality should always be tested within a defined tolerance (see
[*General Standard* **G3.0**](#G3_0)).

- [**PD4.1**]{#PD4_1} *Tests for numeric equality should compare the output of
  of probability distribution functions with the output of code which
  explicitly demonstrates how such values are derived (generally defined in the
  same location in test files).*

A test fulfilling this standard will thus serve the dual purpose of testing the
numeric results of a probability distribution function, and enabling anybody
reading the test file to understand how those numeric results are derived.

- [**PD4.2**]{#PD4_2} *All functions constructed in accordance with **PD2.1** -
  that is, which use a fixed distribution, and which name that distribution as
  an input parameter - should be tested using at least two different
  distributions.*

A package may justifiably rely on one single kind of probability distribution.
Adherence to this standard would then require that the function notionally
accept one other distribution as well, with a test then reflecting an
expectation that results generated with this alternative distribution will
differ somehow.

#### Testing Optimisation and Integration Algorithms

The following standards only apply to packages which use either optimisation
or integration algorithms (or both), and so comply with [**PD3.2**](#PD3_2) and
[**PD3_3**](#PD3_3) for optimisation, or with [**PD3.4**](#PD3_4) and
[**PD3_5**](#PD3_5) for integration.

- [**PD4.3**]{#PD4_3} *Tests of optimisation or integration algorithms should
  compare default results with results generated with alternative values for
  every parameter, including all parameters for the chosen algorithm (whether
  exposed as function inputs or not).*

The following applies to any procedures other than simple one-dimensional
optimisation or integration via routines such as
[`stats::optimize()`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optimize.html)
or
[`stats::integrate()`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/integrate.html).

- [**PD4.4**]{#PD4_4} *Tests of optimisation or integration algorithms should
  compare equivalent results generated with at least one alternative
  algorithm.*

Use of [the `stats::optim()`
function](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optim.html),
for example, would already meet this standard through complying with the
previous **PD4.3**, because `optim()` includes a `method` parameter naming one
of several available optimisation methods. Many optimisation and integration
routines nevertheless implement a single method, in which case adherence to
this standard would require testing results against equivalent results
generated via at least one alternative method.
